-- STG_DIM_APPAREILS
CREATE TABLE STG_DIM_APPAREILS (
    ID INT PRIMARY KEY,
    MARQUE VARCHAR2(100) NOT NULL,
    MODELE VARCHAR2(100) NOT NULL,
    CAPACITE NUMBER NOT NULL,
    ANNEE_FABRICATION NUMBER NOT NULL,
    STATUT VARCHAR2(50) NOT NULL,
    SOURCE_SYSTEM VARCHAR2(50) NOT NULL, -- Système source d'origine
    DATE_LOAD DATE DEFAULT SYSDATE -- Date de chargement des données
);

-- STG_DIM_VOLS
CREATE TABLE STG_DIM_VOLS (
    ID INT PRIMARY KEY,
    APPAREIL_ID INT NOT NULL, -- Remplacement de SK_APPAREIL_ID par ID source
    DATE_VOL DATE NOT NULL,
    VILLE_DEPART VARCHAR2(100) NOT NULL,
    VILLE_ARRIVEE VARCHAR2(100) NOT NULL,
    DISTANCE_VOL NUMBER NOT NULL,
    DUREE_VOL NUMBER NOT NULL,
    STATUT VARCHAR2(50) NOT NULL,
    SOURCE_SYSTEM VARCHAR2(50) NOT NULL,
    DATE_LOAD DATE DEFAULT SYSDATE
);

-- STG_DIM_PARTICIPANTS
CREATE TABLE STG_DIM_PARTICIPANTS (
    ID INT PRIMARY KEY,
    NOM VARCHAR2(100) NOT NULL,
    PRENOM VARCHAR2(100) NOT NULL,
    MILES_ACCUMULES NUMBER,
    STATUT_FIDELITE VARCHAR2(50) NOT NULL,
    AGE NUMBER NOT NULL,
    GENRE VARCHAR2(10) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    TELEPHONE VARCHAR2(20),
    ADRESSE VARCHAR2(200) NOT NULL,
    VILLE VARCHAR2(200) NOT NULL,
    PAYS VARCHAR2(200) NOT NULL,
    SOURCE_SYSTEM VARCHAR2(50) NOT NULL,
    DATE_LOAD DATE DEFAULT SYSDATE
);

-- STG_DIM_VISITEUR
CREATE TABLE STG_DIM_VISITEUR (
    ID INT PRIMARY KEY,
    NOM VARCHAR2(25) NOT NULL,
    PRENOM VARCHAR2(25) NOT NULL,
    MAIL VARCHAR2(100) NOT NULL,
    TELEPHONE VARCHAR2(20),
    SOURCE_SYSTEM VARCHAR2(50) NOT NULL,
    DATE_LOAD DATE DEFAULT SYSDATE
);

-- STG_DIM_CANALDISTRIBUTION
CREATE TABLE STG_DIM_CANALDISTRIBUTION (
    ID INT PRIMARY KEY, 
    NOM_CANAL VARCHAR2(50) NOT NULL,
    TYPE_CANAL VARCHAR2(20) NOT NULL,
    SOURCE_SYSTEM VARCHAR2(50) NOT NULL,
    DATE_LOAD DATE DEFAULT SYSDATE
);

-- STG_DIM_CLASSE
CREATE TABLE STG_DIM_CLASSE (
    ID INT PRIMARY KEY,
    NOM_CLASSE VARCHAR2(20) NOT NULL,
    AVANTAGES VARCHAR2(100) NOT NULL,
    SOURCE_SYSTEM VARCHAR2(50) NOT NULL,
    DATE_LOAD DATE DEFAULT SYSDATE
);

-- STG_DIM_PROMOTION
CREATE TABLE STG_DIM_PROMOTION (
    ID INT PRIMARY KEY,
    NOM_PROMOTION VARCHAR2(30) NOT NULL,
    DESCRIPTION VARCHAR2(100) NOT NULL,
    SOURCE_SYSTEM VARCHAR2(50) NOT NULL,
    DATE_LOAD DATE DEFAULT SYSDATE
);

-- STG_DIM_BILLET
CREATE TABLE STG_DIM_BILLET (
    ID INT PRIMARY KEY,
    CANAL_ID INT NOT NULL, -- Remplacement de SK_CANAL_ID par ID source
    VOL_ID INT NOT NULL, -- Remplacement de SK_VOL_ID par ID source
    TARIF_BASE NUMBER(10, 2) NOT NULL,
    PRIX_ACHAT NUMBER(10, 2) NOT NULL,
    DATE_ACHAT DATE NOT NULL,
    CLASSE VARCHAR2(20) NOT NULL,
    STATUT VARCHAR2(10) NOT NULL,
    SOURCE_SYSTEM VARCHAR2(50) NOT NULL,
    DATE_LOAD DATE DEFAULT SYSDATE
);

-- STG_FAIT_PROMOTION
CREATE TABLE STG_FAIT_PROMOTION (
    ID INT PRIMARY KEY,
    BILLET_ID INT NOT NULL, -- Remplacement de SK_BILLET_ID par ID source
    PROMOTION_ID INT NOT NULL, -- Remplacement de SK_PROMOTION_ID par ID source
    TAUX_PROMOTION NUMBER(5, 2) NOT NULL,
    DATE_DEBUT DATE NOT NULL,
    DATE_FIN DATE NOT NULL,
    SOURCE_SYSTEM VARCHAR2(50) NOT NULL,
    DATE_LOAD DATE DEFAULT SYSDATE
);

-- STG_FAIT_SURCLASSEMENT
CREATE TABLE STG_FAIT_SURCLASSEMENT (
    ID INT PRIMARY KEY,
    BILLET_ID INT NOT NULL, -- Remplacement de SK_BILLET_ID par ID source
    CLASSE_ID INT NOT NULL, -- Remplacement de SK_CLASSE_ID par ID source
    SURCLASSEMENT NUMBER(1) NOT NULL, 
    TARIF_SUPPLEMENTAIRE NUMBER(10, 2),
    SOURCE_SYSTEM VARCHAR2(50) NOT NULL,
    DATE_LOAD DATE DEFAULT SYSDATE
);

-- STG_FAIT_CANALVISI
CREATE TABLE STG_FAIT_CANALVISI (
    ID INT PRIMARY KEY,
    CANAL_ID INT NOT NULL, -- Remplacement de SK_CANAL_ID par ID source
    VISITEUR_ID INT NOT NULL, -- Remplacement de SK_VISITEUR_ID par ID source
    SOURCE_SYSTEM VARCHAR2(50) NOT NULL,
    DATE_LOAD DATE DEFAULT SYSDATE
);

-- STG_FAIT_MILES
CREATE TABLE STG_FAIT_MILES (
    ID INT PRIMARY KEY,
    PARTICIPANT_ID INT NOT NULL, -- Remplacement de SK_PARTICIPANT_ID par ID source
    VOL_ID INT NOT NULL, -- Remplacement de SK_VOL_ID par ID source
    MILES_CALCULES NUMBER NOT NULL,
    SOURCE_SYSTEM VARCHAR2(50) NOT NULL,
    DATE_LOAD DATE DEFAULT SYSDATE
);
