-- STG_DIM_APPAREILS
CREATE TABLE STG_DIM_APPAREILS (
    ID VARCHAR(10) PRIMARY KEY,
    MARQUE VARCHAR(100) NOT NULL,
    MODELE VARCHAR(100) NOT NULL,
    CAPACITE NUMBER NOT NULL,
    ANNEE_FABRICATION NUMBER NOT NULL,
    STATUT VARCHAR(50) NOT NULL
);

-- STG_DIM_VOLS
CREATE TABLE STG_DIM_VOLS (
    ID VARCHAR(10) PRIMARY KEY,
    APPAREIL_ID VARCHAR(10) NOT NULL,
    DATE_VOL DATE NOT NULL,
    VILLE_DEPART VARCHAR(100) NOT NULL,
    VILLE_ARRIVEE VARCHAR(100) NOT NULL,
    DISTANCE_VOL NUMBER NOT NULL,
    DUREE_VOL NUMBER NOT NULL,
    STATUT VARCHAR(50) NOT NULL
);

-- STG_DIM_PARTICIPANTS
CREATE TABLE STG_DIM_PARTICIPANTS (
    ID INT PRIMARY KEY,
    NOM VARCHAR(100) NOT NULL,
    PRENOM VARCHAR(100) NOT NULL,
    STATUT_FIDELITE VARCHAR(50) NOT NULL,
    AGE NUMBER NOT NULL,
    GENRE VARCHAR(10) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TELEPHONE VARCHAR(20),
    ADRESSE VARCHAR(200) NOT NULL,
    VILLE VARCHAR(200) NOT NULL,
    PAYS VARCHAR(200) NOT NULL
);

-- STG_DIM_VISITEUR
CREATE TABLE STG_DIM_VISITEUR (
    ID INT PRIMARY KEY,
    NOM VARCHAR(25) NOT NULL,
    PRENOM VARCHAR(25) NOT NULL,
    MAIL VARCHAR(100) NOT NULL,
    TELEPHONE VARCHAR(20)
);

-- STG_DIM_CANALDISTRIBUTION
CREATE TABLE STG_DIM_CANALDISTRIBUTION (
    ID INT PRIMARY KEY, 
    NOM_CANAL VARCHAR(50) NOT NULL,
    TYPE_CANAL VARCHAR(20) NOT NULL
);

-- STG_DIM_CLASSE
CREATE TABLE STG_DIM_CLASSE (
    ID INT PRIMARY KEY,
    NOM_CLASSE VARCHAR(20) NOT NULL,
    AVANTAGES VARCHAR(100) NOT NULL
);

-- STG_DIM_PROMOTION
CREATE TABLE STG_DIM_PROMOTION (
    ID INT PRIMARY KEY,
    NOM_PROMOTION VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL
);

-- STG_DIM_BILLET
CREATE TABLE STG_DIM_BILLET (
    ID INT PRIMARY KEY,
    CANAL_ID INT NOT NULL,
    VOL_ID VARCHAR(10) NOT NULL,
    TARIF_BASE NUMBER(10, 2) NOT NULL,
    PRIX_ACHAT NUMBER(10, 2) NOT NULL,
    DATE_ACHAT DATE NOT NULL,
    CLASSE VARCHAR(20) NOT NULL,
    STATUT VARCHAR(10) NOT NULL
);

-- STG_FAIT_PROMOTION
CREATE TABLE STG_FAIT_PROMOTION (
    ID INT PRIMARY KEY,
    BILLET_ID INT NOT NULL,
    PROMOTION_ID INT NOT NULL,
    TAUX_PROMOTION NUMBER(5, 2) NOT NULL,
    DATE_DEBUT DATE NOT NULL,
    DATE_FIN DATE NOT NULL
);

-- STG_FAIT_SURCLASSEMENT
CREATE TABLE STG_FAIT_SURCLASSEMENT (
    ID INT PRIMARY KEY,
    BILLET_ID INT NOT NULL,
    CLASSE_ID INT NOT NULL,
    SURCLASSEMENT NUMBER(1) NOT NULL, 
    TARIF_SUPPLEMENTAIRE NUMBER(10, 2)
);

-- STG_FAIT_CANALVISI
CREATE TABLE STG_FAIT_CANALVISI (
    ID INT PRIMARY KEY,
    CANAL_ID INT NOT NULL,
    VISITEUR_ID INT NOT NULL
);

-- STG_FAIT_MILES
CREATE TABLE STG_FAIT_MILES (
    ID INT PRIMARY KEY,
    PARTICIPANT_ID INT NOT NULL,
    VOL_ID VARCHAR(10) NOT NULL,
    MILES_CALCULES NUMBER NOT NULL
);
