-- Drop Tables if they Exist
BEGIN
    FOR rec IN (
        SELECT table_name
        FROM user_tables
        WHERE table_name IN (
            'FACT_PROMO', 'FACT_SURCLASSEMENT', 'FACT_MILES', 'FACT_CANAL_VISITEUR',
            'DIM_APPAREILS', 'DIM_BILLET', 'DIM_PROMOTION', 'DIM_CANAL_DISTRIBUTION',
            'DIM_CLASSE', 'DIM_VISITEURS', 'DIM_VOLS', 'DIM_PARTICIPANTS')
    ) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || rec.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/

-- Create Tables

CREATE TABLE dim_participants (
    participant_sk NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_id NUMBER NOT NULL,
    nom VARCHAR2(100),
    prenom VARCHAR2(100),
    miles_accumules NUMBER,
    statut_fidelite VARCHAR2(50),
    age NUMBER,
    genre VARCHAR2(10),
    email VARCHAR2(100),
    telephone VARCHAR2(20),
    adresse VARCHAR2(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active CHAR(1) DEFAULT 'Y'
);

CREATE TABLE dim_vols (
    vol_sk NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vol_id VARCHAR2(50) NOT NULL,
    date_vol DATE NOT NULL,
    ville_depart VARCHAR2(100),
    ville_arrivee VARCHAR2(100),
    distance_vol NUMBER,
    duree_vol NUMBER,
    statut VARCHAR2(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active CHAR(1) DEFAULT 'Y'
);

CREATE TABLE dim_visiteurs (
    visiteur_sk NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visiteur_id NUMBER NOT NULL,
    nom VARCHAR2(100),
    prenom VARCHAR2(100),
    email VARCHAR2(100),
    telephone VARCHAR2(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active CHAR(1) DEFAULT 'Y'
);

CREATE TABLE dim_classe (
    classe_sk NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classe_id NUMBER NOT NULL,
    nom_classe VARCHAR2(100),
    avantages VARCHAR2(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active CHAR(1) DEFAULT 'Y'
);

CREATE TABLE dim_canal_distribution (
    canal_sk NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canal_id NUMBER NOT NULL,
    nom_canal VARCHAR2(100),
    type_canal VARCHAR2(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active CHAR(1) DEFAULT 'Y'
);

CREATE TABLE dim_promotion (
    promotion_sk NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promotion_id NUMBER NOT NULL,
    nom_promotion VARCHAR2(100),
    description VARCHAR2(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active CHAR(1) DEFAULT 'Y'
);

CREATE TABLE dim_billet (
    billet_sk NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    billet_id NUMBER NOT NULL,
    canal_sk NUMBER NOT NULL REFERENCES dim_canal_distribution(canal_sk),
    vol_sk NUMBER NOT NULL REFERENCES dim_vols(vol_sk),
    tarif_base NUMBER NOT NULL,
    prix_achete NUMBER NOT NULL,
    date_achat DATE,
    promotion_appliquee CHAR(1),
    statut VARCHAR2(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active CHAR(1) DEFAULT 'Y'
);

CREATE TABLE dim_appareils (
    appareil_sk NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appareil_id NUMBER NOT NULL,
    marque VARCHAR2(100),
    modele VARCHAR2(100),
    capacite NUMBER,
    annee_fabrication NUMBER,
    statut VARCHAR2(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    is_active CHAR(1) DEFAULT 'Y'
);

CREATE TABLE fact_canal_visiteur (
    fact_canal_visiteur_sk NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canal_id NUMBER NOT NULL,
    visiteur_sk NUMBER NOT NULL REFERENCES dim_visiteurs(visiteur_sk),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fact_miles (
    fact_miles_sk NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_sk NUMBER NOT NULL REFERENCES dim_participants(participant_sk),
    vol_sk NUMBER NOT NULL REFERENCES dim_vols(vol_sk),
    miles_calcule NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fact_surclassement (
    fact_surclassement_sk NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classe_sk NUMBER NOT NULL REFERENCES dim_classe(classe_sk),
    billet_sk NUMBER NOT NULL REFERENCES dim_billet(billet_sk),
    tarif_supplementaire NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE fact_promo (
    fact_promo_sk NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    billet_sk NUMBER NOT NULL REFERENCES dim_billet(billet_sk),
    promotion_sk NUMBER NOT NULL REFERENCES dim_promotion(promotion_sk),
    taux_promotion NUMBER,
    date_debut DATE,
    date_fin DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
