CREATE TABLE STG_DIM_APPAREILS (
    ID INT PRIMARY KEY,
    SK_APPAREIL_ID VARCHAR(10) NOT NULL,
    MARQUE VARCHAR(100) NOT NULL,
    MODELE VARCHAR(100) NOT NULL,
    CAPACITE NUMBER NOT NULL,
    ANNEE_FABRICATION NUMBER NOT NULL,
    STATUT VARCHAR(50) NOT NULL
);

CREATE TABLE STG_DIM_VOLS (
    ID INT PRIMARY KEY,
    SK_VOL_ID VARCHAR(20) NOT NULL,
    SK_APPAREIL_ID VARCHAR(10) NOT NULL,
    DATE_VOL DATE NOT NULL,
    VILLE_DEPART VARCHAR(100) NOT NULL,
    VILLE_ARRIVEE VARCHAR(100) NOT NULL,
    DISTANCE_VOL FLOAT NOT NULL,
    DUREE_VOL FLOAT NOT NULL,
    STATUT VARCHAR(50) NOT NULL
);

CREATE TABLE STG_DIM_PARTICIPANTS(
    PARTICIPANT_ID INT PRIMARY KEY,
    NOM VARCHAR(100) NOT NULL,
    PRENOM VARCHAR(100) NOT NULL,
    MILES_ACCUMULES NUMBER,
    STATUT_FIDELITE VARCHAR(50) NOT NULL,
    AGE NUMBER NOT NULL,
    GENRE VARCHAR(10) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    TELEPHONE VARCHAR(20),
    ADRESSE VARCHAR(200) NOT NULL,
    VILLE VARCHAR(200) NOT NULL,
    PAYS VARCHAR(200) NOT NULL
);

CREATE TABLE STG_DIM_VISITEUR (
    ID_VISITEUR INT PRIMARY KEY,
    NOM VARCHAR(25) NOT NULL,
    PRENOM VARCHAR(25) NOT NULL,
    MAIL VARCHAR(100) NOT NULL,
    TELEPHONE VARCHAR(20)
);


CREATE TABLE STG_DIM_CANALDISTRIBUTION(
    ID_CANAL INT PRIMARY KEY, 
    NOM_CANAL VARCHAR(50) NOT NULL,
    TYPE_CANAL VARCHAR(20) NOT NULL
);


CREATE TABLE STG_DIM_CLASSE(
    ID_CLASSE INT PRIMARY KEY,
    NOM_CLASSE VARCHAR(20) NOT NULL,
    AVANTAGES VARCHAR(100) NOT NULL
);


CREATE TABLE STG_DIM_PROMOTION(
    ID_PROMOTION INT PRIMARY KEY,
    NOM_PROMOTION VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(100) NOT NULL 
);

CREATE TABLE STG_DIM_BILLET(
    ID_BILLET INT PRIMARY KEY,
    SK_CANAL_ID INT NOT NULL, 
    SK_VOL_ID VARCHAR(20) NOT NULL, 
    TARIF_BASE NUMBER(6,2) NOT NULL,
    PRIX_ACHAT NUMBER(6,2) NOT NULL,
    DATE_ACHAT DATE NOT NULL,
    CLASSE VARCHAR(20) NOT NULL,
    STATUS VARCHAR(10) NOT NULL
);

CREATE TABLE STG_FAIT_PROMOTION(
    ID_PROMO INT PRIMARY KEY,
    SK_BILLET_ID INT NOT NULL,
    SK_PROMOTION_ID INT NOT NULL,
    TAUX_PROMOTION NUMBER(3,2) NOT NULL,
    DATE_DEBUT DATE NOT NULL,
    DATE_FIN DATE NOT NULL
);


CREATE TABLE STG_FAIT_SURCLASSEMENT(
    ID_SURCLASSEMENT INT PRIMARY KEY,
    SK_BILLET_ID INT NOT NULL,
    SK_CLASSE_ID INT NOT NULL,
    SURCLASSEMENT NUMBER(1) NOT NULL, 
    TARIF_SUPPLEMENTAIRE NUMBER(3)
);

CREATE TABLE STG_FAIT_CANALVISI(
    ID INT PRIMARY KEY,
    SK_CANAL_ID INT NOT NULL,
    SK_VISITEUR_ID INT NOT NULL
);

CREATE TABLE STG_FAIT_MILES(
    ID INT PRIMARY KEY,
    SK_PARTICIPANT_ID INT NOT NULL,
    SK_VOL_ID VARCHAR(20) NOT NULL,
    MILES_CALCULES NUMBER(3) NOT NULL
);


